#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

fpath=($HOME/.zprezto/runcoms/zfunc $(rustc --print sysroot)/share/zsh/site-functions /home/linuxbrew/.linuxbrew/share/zsh/site-functions "${fpath[@]}")

compinit
